### ISSUE TITLE
{"level":"error","error":"unsuported filter: ","time":X,"message":"unable to init filter chain"}

### ISSUE THREAD

**Issue by sevospl** [ncarlier/feedpushr#12]
```
[sevos]:<~>$ feedpushr -addr 127.0.0.1:9001 -filter fetch
{"level":"info","component":"store","uri":"boltdb://data.db","time":1580562047,"message":"using BoltDB datastore"}
{"level":"error","error":"unsuported filter: ","time":1580562047,"message":"unable to init filter chain"}
{"level":"fatal","error":"unsuported filter: ","time":1580562047,"message":"unable to init main service"}

```

I'd love to have full text, so I tried to run it with the `fetch` plugin, however it's not working for some reason. Any idea what's wrong?

**Comment by ncarlier** [comment]
Since v2 filters are managed dynamically via the API or the UI.
If you still want to use v1, filter parameter is an URI: https://github.com/ncarlier/feedpushr/tree/v1.2.0#filters
In your case you have to run this command: `feedpushr -addr 127.0.0.1:9001 -filter fetch://`

But I strongly suggest you to use v2.

**Comment by sevospl** [comment]
Gotcha. It turned out that I don't actually need that since it's something that Readflow already does.

If I understood it correctly: Readflow scrapes for HTML and downloads it and I can read it directly on the site. And what Feedpushr does is actually just requesting downloading the articles by parsing RSS feed and pushing then links from it to Readflow, is that correct?
 
The reason as to why I'm not so sure is because I still haven't managed to get it working. Once I'm running feedpushr, I can't see any "add" button in the Outputs section. So I don't know how to make it connecting to Readflow API. There's a lack of docs which also could be considered as my "feature request". It's kind of messy tbh. I believe I kind of got the idea of Readflow + Feedpushr though.

**Comment by ncarlier** [comment]
Well, it's not exactly that:
Readflow fetch article content if **only** the URL is provided.
If the content is provided, Readflow stores the article as is.
That's why you still need the feedpushr fetch plugin for RSS articles.

I think you still use feedpushr v1 because of `go get` behavior. I have to fix Go module path to fix this problem.
Meanwhile, can you try to use the [compiled binary](https://github.com/ncarlier/feedpushr/releases/tag/v2.1.0) (or compile from sources).

You can find some [documentation on how to use Feedpushr with Readflow](https://about.readflow.app/docs/en/third-party/create/feedpushr/).

**Comment by sevospl** [comment]
There's no binary for FreeBSD. This script which you provided doesn't seem to work.

I took a look at this part: https://github.com/ncarlier/feedpushr#for-development and tried to build it with `make` but I got these errors:

```
make: "/usr/home/sevos/feedpushr/Makefile" line 46: Need an operator
make: "/usr/home/sevos/feedpushr/Makefile" line 49: Need an operator
make: "/usr/home/sevos/feedpushr/Makefile" line 50: Need an operator
make: "/usr/home/sevos/feedpushr/Makefile" line 57: Cannot open /makefiles/help.Makefile
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/sevos/feedpushr
```

**Comment by ncarlier** [comment]
GNU Make and BSD Make are slightly different.
You can basically compile the binary using `go build -o feedpushr`

**Comment by sevospl** [comment]
> GNU Make and BSD Make are slightly different.
> You can basically compile the binary using `go build -o feedpushr`

Sorry, I'm not really familiar with Go :) I might have to "study" a little bit about it in my free time.

Meanwhile I did what you told me to but:

`build github.com/ncarlier/feedpushr: cannot load github.com/goadesign/goa/cors: module github.com/goadesign/goa@latest (v2.0.8+incompatible) found, but does not contain package github.com/goadesign/goa/cors`

I don't understand this error.

**Comment by ncarlier** [comment]
Ho yes! Again a module pb. Can you try this:

```bash
$ export GO111MODULE=on
$ go build -o feedpushr
```

**Comment by sevospl** [comment]
> Ho yes! Again a module pb. Can you try this:
> 
> ```shell
> $ export GO111MODULE=on
> $ go build -o feedpushr
> ```

`build github.com/ncarlier/feedpushr: cannot load github.com/goadesign/goa/cors: module github.com/goadesign/goa@latest (v2.0.8+incompatible) found, but does not contain package github.com/goadesign/goa/cors`

The same error, even with this EXPORT. :(

**Comment by sevospl** [comment]
Alright, I have some good news. I've started from the scratch (it's got too messy, my fault) and now managed to build it properly. Looks like it's a new version because I can see this new Outputs panel.
