### ISSUE TITLE
[Feature request] Lack of access UI auth

### ISSUE THREAD

**Issue by sevospl** [ncarlier/feedpushr#13]
Hey! I'm really liking Feedpushr for RSS. It's done nicely, it's fast and scrapes a lot of content very accurately. But there's a lack of any auth - literally anyone can access my UI and play with my RSS feeds, get to know my API key etc.

I think it would be a good move to require some kind of auth, like login and password.

**Comment by ncarlier** [comment]
I'm used to put a reverse proxy (such as Traefik) in front of my services to manage many things, including authentication.
But it's a common and legitimate request. I will add basic authoring support in the next release.

**Comment by sevospl** [comment]
> I'm used to put a reverse proxy (such as Traefik or Kong) in front of my services to manage many things, including authentication.
> But it's a common and legitimate request. I will add basic authoring support in the next release.

That's really awesome! Btw, a little offtopic - which one of them has the easiest way to manage auth? If there was something like https://domains.com/auth=ID, that would be great.

**Comment by ncarlier** [comment]
Both :)
Traefik is more declarative and designed to be integrated with other service (Consul, K8S, Docker, ... ). Kong can be declarative but it's designed works on its own with a DB and is manageable with an API or with GUI ([Kong](https://github.com/pantsel/konga)). About your example, it's safer to have an API key provided by HTTP headers (`X-API-Key` or `Authorization` with basic auth or bearer) and not by the URL.

**Comment by ncarlier** [comment]
Hello, basic authentication has been added : https://github.com/ncarlier/feedpushr#authentication
Feedback are welcome before including this update in the next version.

**Comment by ncarlier** [comment]
Done.

**Comment by sevospl** [comment]
> Done.

It's working well. :) Have been using it before it's got released (just pulled this commit via git :D). Thanks a lot!
