### ISSUE TITLE
failed to compile ui

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#14]
Hi,

Hope you are all well !

while running the command `npm run start`, I have the following error:

```javascript
Failed to compile
/app/src/feeds/FeedList.tsx
TypeScript error in /app/src/feeds/FeedList.tsx(23,16):
Generic type 'Column<RowData>' requires 1 type argument(s).  TS2314

    21 | }
    22 | 
  > 23 | const columns: Column[] = [
       |                ^
    24 |   { 
    25 |     title: 'Aggregation',
    26 |     render: (feed: Feed) => ( !!feed && <FeedControl feed={feed} /> ),
```

Any way to fix it ? Thanks in advance.

Have a good week-end !

Cheers,
X

**Comment by ncarlier** [comment]
It seems that you have upgrade [material-table](https://github.com/mbrn/material-table). The recent revision seems to use the generic type for the column but not the version used: 1.40.1

**Comment by x0rzkov** [comment]
nope, it is 1.40.1. I tried to improve a bit the repo by adding a docker-compose but this problem prevents it to make it work.

https://github.com/x0rzkov/feedpushr

**Comment by x0rzkov** [comment]
Why don't u use https://github.com/marmelab/react-admin ? Would be simplier for adding new tables and sections.

**Comment by ncarlier** [comment]
You have updated many dependencies in your fork and `material-table` is one of them.
Your are using material-tab 1.57.2: https://github.com/x0rzkov/feedpushr/blob/master/ui/package.json#L15 

React Admin is a bit overkill regarding my needs. FYI, all HTML assets are embedded into the binary. You don't need an extra server to serve them. The lighter the assets, the better ;)

**Comment by x0rzkov** [comment]
fixed it by reforking the repo
