### ISSUE TITLE
twitter plugin credentials

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#15]
Hi,

Hope you are doing well !

How do you pass the twitter's credentials to the twitter plugin ?
Can you prodive an example of command line ?

Cheers,
X

**Comment by ncarlier** [comment]
You only have to use the UI to add a Twitter output then configure the output: 
![twitter](https://user-images.githubusercontent.com/795995/74610762-6bdc5480-50f6-11ea-8ee2-39ba0ab34035.png)

**Comment by x0rzkov** [comment]
Another question, on the topic of plugins, can we load several plugin at the same time ?

```bash
./feedpushr --log-pretty --plugin ./feedpushr-twitter.so --plugin ./feedpushr-rake.so --plugin ./feedpushr-mastodon.so
```

I would like to develop a contrib for yake.

Ref. https://github.com/LIAAD/yake

**Comment by x0rzkov** [comment]
ps. je parle francais aussi

**Comment by ncarlier** [comment]
Yes, you can. You can also ignore `--plugin` if all your plugins are in the current directory. Feedpushr will try to load them all.

Having a Yake plugin would be great. I just wonder how to integrate Python with Go?

- C binding with something like https://github.com/DataDog/go-python3
- Exec a sub process and fetch STDOUT result
- Use HTTP API
- ...

**Comment by x0rzkov** [comment]
just with docker-compose and use the rest api for the moment

**Comment by x0rzkov** [comment]
![Screenshot 2020-02-17 at 10 07 37](https://user-images.githubusercontent.com/56916043/74639084-8c93c100-516d-11ea-9dfa-99e7aa85367d.png)

I don't have mastodon and rake.

**Comment by ncarlier** [comment]
Available plugins are put in cache by the browser. If you start/stop the daemon with other plugins configuration, your browser will not show the correct list except if you restart the browser session (or remove the `filterSpecs` and `outputSpecs` keys from your session storage).

**Comment by ncarlier** [comment]
Can you create another Feature Request for Yake (this in order to not mix threads 😉 )?

**Comment by x0rzkov** [comment]
I have done it, I think we can close this issue too
