### ISSUE TITLE
not aggregating feeds despite being activated

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#16]
Hi again,

Hope you are doing well !

I doesn't seem to be aggregating my feeds, counters remain at zero.

![Screenshot 2020-02-17 at 10 03 29](https://user-images.githubusercontent.com/56916043/74639335-09bf3600-516e-11ea-9404-b94719d2628c.png)

Nothing happened after the 54s.

Any action that I missed ?

Feeds:
- https://feeds.feedburner.com/TheHackersNews
- https://feeds.feedburner.com/PentestTools
- https://www.hackerfactor.com/blog/index.php?/feeds/index.rss2

Cheers,
X

**Comment by ncarlier** [comment]
If no output is configured, feeds are not aggregated.
That said, I know that there is an additional latency when activating the feeds **after** the outputs. I need to investigate that.

**Comment by x0rzkov** [comment]
it works like a charm for twitter, just tested it on another twitter account
