### ISSUE TITLE
[Feature request] masonry style dashboard with articles

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#17]
Hi again,

Hope you are doing well !

Would be awesome to have some masonry backed dashboard to display the aggregated feeds' articles.

Cheers,
X

**Comment by ncarlier** [comment]
I'm sorry, but what do you mean by "masonry dashboard"?

**Comment by x0rzkov** [comment]
Normal a boring dahsboard would be
![73948569-72e6b400-48f9-11ea-99dc-dc3373433680](https://user-images.githubusercontent.com/56916043/74642031-92d86c00-5172-11ea-97db-d6ca4f5f779b.png)

A masonry dashboard would be
![73948938-f3a5b000-48f9-11ea-92e1-fa09b380ac48](https://user-images.githubusercontent.com/56916043/74642061-a1268800-5172-11ea-8d40-992859e85041.png)

References:
- https://github.com/paulcollett/react-masonry-css
	- demo: https://paulcollett.github.io/react-masonry-css/demo/

**Comment by ncarlier** [comment]
Feedpushr does not store feed articles but transmits them to anything that has an API.
It was initially designed to be a RSS client for [Readflow](readlow.app) .

BTW thanks for the reference.

**Comment by x0rzkov** [comment]
Awesome, I'll have try right now.

I guess we can close this issue also
