### ISSUE TITLE
[Feature Request] add yake 

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#18]
Hi,

Hope you are all well !

It would be awesome to create a contrib for yake. 
https://github.com/LIAAD/yake

The idea would be to create a docker-compose and use the rest api of yake.
https://github.com/LIAAD/yake#option-2-rest-api-server-in-a-docker-container

I will fork the repo and try to implement it asap.

Any advice or insights to share upfront ?

Cheers,
X

**Comment by ncarlier** [comment]
Some insights:
- put a sample docker-file into the `contrib/yake` folder.
- store keywords list inside meta: `article.Meta["keywords"] = keywords` (like for [RAKE](https://github.com/ncarlier/feedpushr/blob/master/contrib/rake/plugin.go#L94))
- Plugin spec should be something simple like:

```go
var spec = model.Spec{
	Name: "yake",
	Desc: "Extract keywords bla bla bla...",
	PropsSpec: []model.PropSpec{
		{
			Name: "endpoint",
			Desc: "Yake API endpoint",
			Type: model.URL,
		},
		{
			Name: "maxNgramSize",
			Desc: "Maximum size of the ngram (default: 3)",
			Type: model.Number,
		},
		{
			Name: "numberOfKeywords",
			Desc: "Number of keywords (default: 10)",
			Type: model.Number,
		},
                {
			Name: "lang",
			Desc: "Language (default: en)",
			Type: model.Text,
		},
	},
}
```

- Nice to have: language should be auto detected

**Comment by x0rzkov** [comment]
awesome ! thanks

**Comment by x0rzkov** [comment]
Can we chat over twitter DM ? it seems that you have blocked this feature
