### ISSUE TITLE
plugin rake is not appearing

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#19]
Hi again,

Hope you are all well !

In order to build the yake module, I wanted to test the rake plugin.

```bash
./feedpushr --log-pretty --plugin feedpushr-rake.so
```

Nowhere, where to configure the rake parameters. 

Am I missing something ?

Cheers,
X

**Comment by ncarlier** [comment]
RAKE is a filter. You should retrieve it when you add a filter:
![filters](https://user-images.githubusercontent.com/795995/74658733-2f126b00-5193-11ea-931b-9eaf87806bc9.png)

**Comment by lucmichalski** [comment]
does not appear in this section

**Comment by ncarlier** [comment]
Have you restart your Browser session (or remove session storage keys) ?

**Comment by x0rzkov** [comment]
all good for me, I opened in brave.
