### ISSUE TITLE
[Feature Request] add pagination to feed list

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#20]
Hi,

I imported 1200 feeds into feedpushr and can see only 100.

I would be awesome to add pagination to browser other feeds.

Here is the opml file for example:
https://github.com/x0rzkov/feedpushr/blob/master/resources/security.opml

Cheers,
X

**Comment by ncarlier** [comment]
1200 feeds! Impressive 👀 
Indeed, it is hard-coded because I thought it was complicated to follow more than 100 feeds. But after all, usage cases can vary. So I'm going to add a pagination.

**Comment by x0rzkov** [comment]
Waiting for that with such impatience :-)

**Comment by ncarlier** [comment]
It's available on the master. Happy testing!

**Comment by lucmichalski** [comment]
will test it right now :-) I have doe 3 contribs already, will debrief you later

**Comment by x0rzkov** [comment]
Quick feedback:
- it is awesome to navigate through more than 2000 feeds, thanks again
- the search box is not searching the full scope of feeds, only the current page
- it is a little bit slow maybe to gzip the api response would make things go quicker

**Comment by ncarlier** [comment]
Performance issue is not related to the server side (~5ms). It's an issue of [material-ui](https://github.com/mui-org/material-ui) which seems to be caused by the Tooltip component (according to the React profiler). Further investigation is required.

**Comment by lucmichalski** [comment]
There is a bug when you load a new page from the pagination links, checkboxes are not updated.

**Comment by lucmichalski** [comment]
Also, the search box, in the top right corner, in the feed list, is not searching the full list of feeds but only the current page.

**Comment by ncarlier** [comment]
About searching that's not trivial. The database is a simple Key/Value store (powered by Bolt). This implies the addition of an indexing engine (such as [bleve](https://github.com/blevesearch/bleve) for example). It's a nice to have but but with a low priority.
