### ISSUE TITLE
unsupported content type: content-type

### ISSUE THREAD

**Issue by lucmichalski** [ncarlier/feedpushr#24]
Hi,

Hope you are all well !

When I want to add this feed, https://morioh.com/feed, it triggers an alert box saying "unsupported content type: content-type".

Any explanation to why it happens ? as it sounds a proper rss feed.

Cheers,
Luc

**Comment by ncarlier** [comment]
This value is extracted from the `Content-Type` HTTP header. It's an invalid value. It should be something such as `text/xml`, `application/xml` or `text/html` (In this last case, the feed URl is extracted from HTML page header).
