### ISSUE TITLE
cannot make plugins

### ISSUE THREAD

**Issue by x0rzkov** [ncarlier/feedpushr#26]
Hi,

Hope you are all well and congrats for this new release :-) !

While building the plugins, I have the following error:

```bash
feedpushr % make plugins
>>> Building: feedpushr-twitter.so 7a823e0 for linux-amd64 ...
# github.com/ncarlier/feedpushr-contrib/twitter
loadinternal: cannot find runtime/cgo
/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[1]: *** [plugin] Error 2
make: *** [plugins] Error 2
```

Any reason why ? Is there a way to sort it out ?

Cheers,
X

**Comment by ncarlier** [comment]
Hi, no idea... it's seems related to OSX:

- https://github.com/golang/go/issues/30986
- https://github.com/golang/go/issues/28704

As far as plugins are concerned, nothing has changed with v2 regarding the building process. Do you have the same pb on v2?

**Comment by lucmichalski** [comment]
nope, I was building them successfully.

**Comment by lucmichalski** [comment]
We should create a docker-compose and dockerfiles. isn it ?

**Comment by ncarlier** [comment]
> nope, I was building them successfully.
Can you retry to build them in v2? Honestly, I don't see what could have changed.

> We should create a docker-compose and dockerfiles. isn it ?
There's already a [Dockerfile](https://github.com/ncarlier/feedpushr/blob/master/Dockerfile) and a [Docker image](https://hub.docker.com/r/ncarlier/feedpushr/). I don't see the need to have a Docker composes file because there is nothing to... compose 😉 It's a single binary.

**Comment by lucmichalski** [comment]
but the UI ?

**Comment by ncarlier** [comment]
The user interface is embedded into the binary.

I'm using github.com/rakyll/statik to do that: https://github.com/ncarlier/feedpushr/blob/master/Makefile#L87

**Comment by lucmichalski** [comment]
Found the issue for making plugins.
https://github.com/ncarlier/feedpushr/blob/master/Makefile#L12
I changed to darwin and it works.

**Comment by ncarlier** [comment]
Fixed by https://github.com/ncarlier/feedpushr/commit/79e77c154dfde82159169204c4ed42c222edba4d
