### ISSUE TITLE
How to use RDBMS plugin through docker?

### ISSUE THREAD

**Issue by windware-ono** [ncarlier/feedpushr#51]
I first tried to place the plugin in the environment variable, (not sure if the path was right and I tried several others like `feedpushr-rdbms.so`, `contrib/rdbms/feedpushr-rdbms.so`,

```
working_dir: /var/opt/feedpushr
environment:
  - FP_PLUGINS=plugins/feedpushr-rdbms.so
```

but those paths failed with `realpath failed` in the log.

I also tried to place `feedpushr-rdbms.so` from the downloaded release file of the same version of the `latest` docker image at `3.2.0` but this failed with `plugin was built with a different version of package internal/abi`.

Is there a way to add an output plugin to the docker instance?

**Comment by ncarlier** [comment]
The official Docker images include all plugins into this directory: `/usr/local/share/feedpushr/`
Set your env variable like this: `FP_PLUGINS=/usr/local/share/feedpushr/feedpushr-rdbms.so`

**Comment by windware-ono** [comment]
Thank you!
Maybe it's good to be mentioned in the document for docker installation.
