### ISSUE TITLE
Not all articles are being sent to output plugin?

### ISSUE THREAD

**Issue by windware-ono** [ncarlier/feedpushr#52]
I've added an ATOM feed from [https://status.digitalocean.com/history.atom](https://status.digitalocean.com/history.atom) and the feed screen is showing `25` as `Aggregation success` but in the output plugin that I've configured to send to Mattermost (I do not have any rate limiting in Mattermost) with `http` plugin, I only get the latest 2 article entries but should it not send the entire 25 entries to the output plugin once the feed and the output settings are added?

I've also added [https://status.linode.com/history.atom](https://status.linode.com/history.atom) and this one sent out 4 articles to the output plugin and another from [https://www.cloudflarestatus.com/history.atom](https://www.cloudflarestatus.com/history.atom) sent 9 articles to the output plugin and seems it's behaving inconsistently.

**Comment by ncarlier** [comment]
Only recent articles are sent. This duration is linked to the cache retention time: https://github.com/ncarlier/feedpushr/blob/master/etc/default/feedpushr.env#L16
In other words, if you have a 48-hour cache, only the last 2 days' articles will be sent.

**Comment by windware-ono** [comment]
Thank you for clarifying.
