### ISSUE TITLE
Repeated output of same articles

### ISSUE THREAD

**Issue by windware-ono** [ncarlier/feedpushr#53]
I've added this feed and it seems both `http` and `rdbms` output keep repeating the same entries over and over on every interval.

[https://ubuntu.com/security/notices/atom.xml](https://ubuntu.com/security/notices/atom.xml)

**Comment by ncarlier** [comment]
This feed is updating constantly the entry update date. Even if the entry is not updated!?! They should update the feed date but not the entry.

**Comment by ncarlier** [comment]
Switching to the RSS feed should fix this : https://ubuntu.com/security/notices/rss.xml

**Comment by windware-ono** [comment]
Ah, sorry that it was the feed that is behaving weird... and thanks for finding out the RSS version works fine.

**Comment by lukedoomer** [comment]
I am facing the same problem. 
I added a feed, [https://www.ptt.cc/atom/Lifeismoney.xml](url)
How to ignore the <updated> tag

**Comment by ncarlier** [comment]
The (Atom specification)[https://validator.w3.org/feed/docs/atom.html] is very specific about this element: 

> Indicates the last time the entry was modified in a significant way. This value need not change after a typo is fixed, only after a substantial modification.

I only see these workarounds:

- contact the publisher to fix his feed
- create small proxy that remove (or fix) the updated element
- use a online service to convert Atom to RSSv2 without update element : https://feedmix.novaclic.com/atom2rss.php?source=https%3A%2F%2Fwww.ptt.cc%2Fatom%2FLifeismoney.xml
