### ISSUE TITLE
chore(install) install feedpushr using Ansible

### ISSUE THREAD

**Issue by slundi** [ncarlier/feedpushr#57]
Hi,

I made a 1st version of an Ansible to install Feedpushr: https://github.com/slundi/ansible_feedpushr

It uses latest release binary to install Feedpushr. But plugins are only available for AMD64 arch because they are not on the ARM and ARM64 archive.

Is it OK to add the Ansible install doc on the `README.md`?

**Comment by ncarlier** [comment]
Hi,

it's a great work! I will add your alternative installation method to the README.
Regarding plugins, Golang cross compilation is not friendly with plugins. I have some trouble with ARM and Windows.

Regards

**Comment by slundi** [comment]
Hi,
Thanks, I can't help you on the cross-compilation with Golang. With Github workflow there is buildx and QEmu that is used for cross-compilation but I failed my RUST tests :(

By the way, do you know how the plugin configuration is loaded? Does it use env variables?

Regards

**Comment by ncarlier** [comment]
Output and Filter's configuration are stored inside the DB (Bolt). The configuration is managed by the API or the UI.
