### ISSUE TITLE
[Output plugin request] : Apprise

### ISSUE THREAD

**Issue by tillcash** [ncarlier/feedpushr#60]
Thanks for the software.

Is it possible to add Apprise as output plugin?

https://github.com/caronc/apprise

**Comment by ncarlier** [comment]
Hi, thank you for your interest!
This is a good idea but I wonder if the HTTP plugin is not enough ?
You can configure the HTTP plugin as follows:

- Target URL: `http://localhost:8000/notify`
- Content Type: `JSON`
- Payload:

```json
{
  "urls": "mailto://user:pass@gmail.com",
  "title": "{{.Title}}",
  "body": "{{.Content}}",
  "format": "html"
}
```

Or using Apprise tags:

- Target URL: `http://localhost:8000/notify/<APPRISE_KEY>`
- Content Type: `JSON`
- Payload:

```json
{
  "tag": "example",
  "title": "{{.Title}}",
  "body": "{{.Content}}",
  "format": "html"
}
```

**Comment by tillcash** [comment]
It helps. Thanks.
