### ISSUE TITLE
How to make condition work in case insensitive?

### ISSUE THREAD

**Issue by lukedoomer** [ncarlier/feedpushr#61]
In other words, how to make matches and include in EXPR engine work in case insensitive?

**Comment by ncarlier** [comment]
`matches` works with a Go regular expression: https://pkg.go.dev/regexp/syntax@master
So you can use this kind of expression: `Title matches "(?i)HeLLoWoRLD"`

`in` is not insensitive. However I will consider adding string manipulation functions such as toLower or toUpper as I already did in another project (https://github.com/ncarlier/readflow/blob/master/pkg/rule-engine/processor.go#L70)

**Comment by ncarlier** [comment]
Close by https://github.com/ncarlier/feedpushr/commit/11d053ff4ae191e9f6259bb2a5f5ee502374c87c
