### ISSUE TITLE
Cannot add slow feed as DefaultTimeout is too small

### ISSUE THREAD

**Issue by lukedoomer** [ncarlier/feedpushr#62]
```
// DefaultTimeout for HTTP requests
const DefaultTimeout = time.Duration(5 * time.Second)
```

I self-hosted RSS-Bridge on Celeron PC and using its component, [XPathBridge](https://github.com/rss-bridge/rss-bridge) which is resource demanding task.
The default 5-second timeout leads to `context canceled`.
May I ask you to increase the default timeout or add a settings for it?

**Comment by ncarlier** [comment]
You can configure the aggregator timeout: https://github.com/ncarlier/feedpushr/blob/master/etc/default/feedpushr.env#L78

**Comment by lukedoomer** [comment]
How can I miss such important setting. Thanks!
