### ISSUE TITLE
Can't add RSS feeds from Reddit

### ISSUE THREAD

**Issue by pztrn** [ncarlier/feedpushr#68]
Hey, I'm on 3.3.1 in Docker.

Can't add RSS feeds from Reddit. In web interface it says "http error: 403 Forbidden", yet curl downloads feed (for example, https://www.reddit.com/r/selfhosted.rss) just fine, from the very same machine.

**Comment by ncarlier** [comment]
Hi! Thank you for pointing out this problem. This is a problem that occurs only with the default golang HTTP client (seems to be related to HTTP2 support). I will correct this.
