### ISSUE TITLE
Mail output plugin - no Date

### ISSUE THREAD

**Issue by pztrn** [ncarlier/feedpushr#70]
I'm on 3.3.1 in Docker.

Using mail output plugin results in emails being without dates at all. No such header added [here](https://github.com/ncarlier/feedpushr/blob/master/pkg/output/plugins/email_plugin.go#L171).

Some mail clients does not show any date for mails if no such header present. This not a problem for Thunderbird as it shows date on which email was received, but for KMail2, for example, a huge one:

![изображение](https://user-images.githubusercontent.com/869402/206230826-5146a6d0-5fd6-490d-82e9-c8fba3a35f00.png)

Those "неизвестное" should be a date on which mail was sent.

**Comment by ncarlier** [comment]
Thanks for the issue report.
