### ISSUE TITLE
Empty on restart

### ISSUE THREAD

**Issue by pieman3000** [ncarlier/feedpushr#85]
Running a feedpushr in a docker container, when the container is restarted all of the data disappears.

I assume the solution is to set up a volume, however the folders to use in the volume are not listed in the repo.

Could someone please let me know which folders I need to link.

Thanks

**Comment by ncarlier** [comment]
Hi,

By default the database is next to the executable. You can configure the database location: https://github.com/ncarlier/feedpushr/blob/master/etc/default/feedpushr.env#L27

Docker usage example:

```bash
docker run -e FP_DB=boltdb:///var/opt/feedpushr/data.db  -v ./data:/var/opt/feedpushr  ncarlier/feedpushr
```

**Comment by pieman3000** [comment]
That seems to have fixed the problem.

Many thanks, especially for the quick reply :)
