### ISSUE TITLE
OPML imports in a strict mode

### ISSUE THREAD

**Issue by obax** [ncarlier/feedpushr#86]
Hi, @ncarlier - thank you for all the good work.

I have a use case where I would like to have an OPML file define a portable source of truth for which URLs to follow.

Importing it via the API would make feedpushr obey the items included in the last import, discarding the rest, which differs from the append-only approach as it exists now.

I'm happy to provide an example of this. The `POST` endpoint could take a payload/param signalling this `strict` import mode.
Is there any appetite for it / pitfall to be aware of before I make a start?

**Comment by ncarlier** [comment]
A kind of "in-place" import. Yes it's a good idea. Regarding  pitfalls ... I hope not :)
