### ISSUE TITLE
Send email to multiple to: addresses

### ISSUE THREAD

**Issue by Wobak** [ncarlier/feedpushr#88]
Hello,

Thank you for the hard work so far !

Unless I'm mistaken, the email output entry can only send an email to a single email address. 

I am using feedpushr to send a blog output to multiple friends while parsing its RSS feed. Having to add a single output per person is a bit tedious. What would it take to have multiple email addresses in the "To" field of outputs ?

Thanks,

**Comment by Wobak** [comment]
Hello @ncarlier, any update on this?

**Comment by ncarlier** [comment]
Last commit should fix that. Regards.
