### ISSUE TITLE
Feature request: email_bcc instead of email_to

### ISSUE THREAD

**Issue by Wobak** [ncarlier/feedpushr#89]
Hello again ! 

As you added quite nicely the feature to use a single output for multiple email addresses through https://github.com/ncarlier/feedpushr/issues/88, could it be possible to choose to use the bcc field instead of the to: field to avoid people knowing all the receivers' emails ?

Thanks!

**Comment by ncarlier** [comment]
Done :)

**Comment by Wobak** [comment]
Thank you !

**Comment by Wobak** [comment]
Hello,

I don't see that config in the email version of the webUI, am I missing something?

**Comment by ncarlier** [comment]
Hello, it's maybe because plugins schema are stored into the browser session storage. You may have to clean website local data in order to have the last version.
